### PR TITLE
chore(#13): migrated to WireMock v3, dropped support for Java 8, 

### LINKED ISSUE #13: WireMock 3 compatibility
As mentioned in https://github.com/wiremock/wiremock/issues/2323
it would be nice to have extension compatible with WireMock 3
(dropping support for Java 8, etc.)

### PR DESCRIPTION
**Pull request by petrandreev**
- WireMock 3 (https://github.com/wiremock/wiremock/issues/2323) supported now
- aligned gradle with WireMock 3
- ditched deprecation warnings in tests
- bumped few libs

Closes #13

### CODE REVIEW

**Comment by MasonM** [comment]
Thanks for your contribution! 

I'm fine dropping Java 8 support, but the Github workflow needs to be updated 
https://github.com/MasonM/wiremock-jwt-extension/blob/864594b1935d44e7ca63777cf42ba7d3fbfd898a/.github/workflows/gradle.yml#L22

I believe that's why the tests are failing with "invalid source release: 11" - https://github.com/MasonM/wiremock-jwt-extension/actions/runs/6158424799/job/16737798842?pr=14

**Comment by petrandreev** [comment]
Hi Mason, checks passed- what can I do next?

**Comment by MasonM** [comment]
Thanks Pëtr. I'm a bit busy at the moment, but I should be able to review
this on Friday

**Review by MasonM — APPROVED** [review]
This is great, thanks!

**Comment by MasonM** [comment]
Hmm, I tried to publish and oss.sonatype.org is given me 502s:
```
$ ./gradlew publish --stacktrace                                                               -- INSERT -- [21:47:42]
> Task :publishMavenJavaPublicationToSnapshotsRepository FAILED                                                                                                 
                                                                                                                                                                
FAILURE: Build failed with an exception.                                                                                                                        
                                                                                                                                                                
* What went wrong:                                                                                                                                              
Execution failed for task ':publishMavenJavaPublicationToSnapshotsRepository'.                                                                                  
> Failed to publish publication 'mavenJava' to repository 'snapshots'                                                                                           
   > Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/com/github/masonm/wiremock-jwt-extension/1.0.0/wiremock-jwt-extension-1.0.0.jar'. Received status code 502 from server: Bad Gateway            
```

Guessing it's an incompatibility with the `maven-publish` plugin. I'll look more into this tomorrow

**Comment by MasonM** [comment]
Okay, I think I fixed it by removing the snapshot repository, which I don't really use anyway. This should be up on Maven Central shortly. 

Thanks again!

**Pull request merged**
